// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package meta

// FilterMethods returns a copy of Methods, omitting elements that are rejected by the given function.
// The n argument determines the maximum number of elements to return (n < 1: all elements).
func (f *File) FilterMethods(fn func(*Method) bool, n int) Methods {
	cap := n
	if n < 1 {
		cap = len(f.Methods)
	}
	result := make(Methods, 0, cap)
	for i := range f.Methods {
		if fn(f.Methods[i]) {
			if result = append(result, f.Methods[i]); len(result) >= cap {
				return result
			}
		}
	}
	return result
}
