// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package cat

import (
	""
)

// GetUuid returns the value of Uuid.
func (c Cat) GetUuid() uuid.UUID {
	return c.Uuid
}
